### ISSUE TITLE
ValueError: The model's max seq len (4096) is larger than the maximum number of tokens that can be stored in KV cache (3664). Try increasing gpu_memory_utilization or decreasing max_model_len when initializing the engine.

### ISSUE THREAD

**Issue by mohsenMahmoodzadeh** [basalam/product-catalog-generator#10]
I followed the readme guidelines to get inferences from both models. However, I got the following error:

```
ValueError: The model's max seq len (4096) is larger than the maximum number of tokens that can be stored in KV cache (3664). Try increasing gpu_memory_utilization or decreasing max_model_len when initializing the engine.
```

I use the google colab with the following configuration:
```
python=3.10.12
transformers==4.36.2
torch==2.1.2
vllm==0.2.7
```

It is worth noting I'm using the versions w.r.t requirements.txt of the repository. How can I solve this problem?

**Comment by MrzEsma** [comment]
Hi. This error is related to the `vllm` framework and the reason for this problem is that the GPU you are using has limited VRAM capacity and cannot handle this `max_model_len` (4096). As explained in the error message itself, try restarting `vllm` with either a higher `gpu_memory_utilization` or a lower `max_model_len`.
See also this [issue](https://github.com/vllm-project/vllm/issues/2418).
